name: Compile and Release LaTeX Document

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permette di avviare il workflow manualmente

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          compiler: pdflatex  # Puoi usare xelatex o lualatex se necessario
          latexmk_use_lualatex: false
          latexmk_shell_escape: true

      - name: Read version from file
        id: get_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: main.pdf
          tag_name: ${{ env.VERSION }}
          release_name: "Release ${{ env.VERSION }}"
          body: "Versione ${{ env.VERSION }} del documento PDF."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
