name: Compile and Release LaTeX Document

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Permessi per creare la release

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          compiler: pdflatex

      - name: Read version and changelog from file
        id: get_version
        run: |
          VERSION=$(head -n1 version.txt)  # Prima riga = numero versione
          CHANGELOG=$(tail -n +2 version.txt | sed 's/^# //')  # Rimuove il simbolo # dai commenti
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: main.pdf
          tag_name: ${{ env.VERSION }}
          release_name: "Release ${{ env.VERSION }}"
          body: "${{ env.CHANGELOG }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
